from argparse import RawTextHelpFormatter, ArgumentParser

from loader import *
from translator import *
from runtime_info import *
from builder import *
from definition import *
   

if __name__ == "__main__":
    p = ArgumentParser(formatter_class=RawTextHelpFormatter)
    p.add_argument('asm_file', help='path to the input asm file which should be generated by Uroboros')

    args = p.parse_args()
    asm_file = args.asm_file

    l = Loader(asm_file)
    builder = Builder(l.sections['.text'])
    p = builder.build_program()

